### PR TITLE
Issue#44

### PR DESCRIPTION
**Pull request by RohitP2005**
## Description

- Language Used: JavaScript (React)
- Approach Used: Added phone number validation and updated the registration form
- Question(s) Solved: Ensured that the phone number entered in the form is a valid 10-digit number
- Issue(s) related: #44

- What does this PR fix or add?
  - Adds validation for the phone number to ensure it is exactly 10 digits long.
  - Updates the form to display an error message when the phone number does not meet the requirement.
- Are there any dependencies or related issues?
  - No additional dependencies.
- Any special instructions for testing?
  - Ensure that the phone number field accepts only 10-digit numbers.
  - Test the form submission with both valid and invalid phone numbers to verify correct validation behavior.

## Type of Change

Please select the appropriate option by putting x (example- [x]):

- [ ] Bug fix
- [x] New feature
- [x] Refactoring
- [ ] Documentation update

## Checklist

- [x] I have tested my changes locally.
- [x] I have added any necessary tests.
- [ ] I have updated the documentation (if applicable).
- [x] I have followed the coding style of the project.
- [x] My code is ready for review.

### CODE REVIEW

**Comment by AbhilashK26** [comment]
Attach screenshots or demo video.
Did you try to register something dummy to ensure successful registration is not violated by this change? if not, Please once try to register one dummy person and check it is added or not in your localhost server.(consider the case where multiple skills can be added for a user)

**Comment by RohitP2005** [comment]
okay

**Comment by RohitP2005** [comment]
I have updated as requested

**Comment by AbhilashK26** [comment]
> I have updated as requested

Please attach the screenshots or demo video .

**Comment by RohitP2005** [comment]
test
test1
Examples of a succesfully registration

**Pull request merged**
