### PR TITLE
home button added

### PR DESCRIPTION
**Pull request by RohitP2005**
# Pull Request Template

Thank you for your contribution to CodeBase! Please provide the following information to help us review your pull request.

## Description

- **Language Used:** HTML, Tailwind CSS  
- **Approach Used:** Added a static "Home" button styled using Tailwind CSS.  
- **Question(s) Solved:** N/A  
- **Issue(s) related:** N/A  

This pull request adds a visually styled "Home" button using the `<button>` tag. The button is styled with Tailwind CSS for a clean appearance, with hover and focus effects for enhanced user experience. The button currently has no functionality and is intended as a static UI element.

- **What does this PR fix or add?** Adds a styled static "Home" button to the UI.  
- **Are there any dependencies or related issues?** No dependencies.  
- **Any special instructions for testing?** Ensure the Tailwind CSS framework is properly configured to view styles.

## Type of Change

Please select the appropriate option by putting `x` (example- `[x]`):

- [x] New feature

## Checklist

- [x] I have tested my changes locally.  
- [x] I have followed the coding style of the project.  
- [x] My code is ready for review.

## Screenshots

Home Button

---

We will review your changes and get back to you soon. Thank you for contributing to CodeBase!

### CODE REVIEW

**Comment by AbhilashK26** [comment]
Keep the Codebase logo as it is and add a Home button between the Filter button and the Login button.

**Comment by RohitP2005** [comment]
Okay

**Comment by RohitP2005** [comment]
> Keep the Codebase logo as it is and add a Home button between the Filter button and the Login button.

I updated those changes as requested

**Comment by MegaReXR** [comment]
Share your updated screenshot.

**Comment by RohitP2005** [comment]
image

**Pull request merged**
